### ISSUE TITLE
Kwestie do wyjaśnienia

### ISSUE THREAD

**Issue by mateuszstaszkow** [mateuszstaszkow/ganc_glodowo#16]
- [x] Jaka jest dokładna lokalizacja działek?
- [x] Jaki font do strony?
- [x] #23

**Comment by qbuch** [comment]
1.https://mapy.geoportal.gov.pl/imap/Imgp_2.html?identifyParcel=220605_2.0003.280/3
https://mapy.geoportal.gov.pl/imap/Imgp_2.html?identifyParcel=220605_2.0003.280/2
2. Myślę, że taki będzie ok https://fonts.google.com/specimen/Open+Sans
3. Biel i zieleń dobrze pasuje
