### ISSUE TITLE
Jaka paleta kolorów?

### ISSUE THREAD

**Issue by qbuch** [mateuszstaszkow/ganc_glodowo#23]

**Comment by mateuszstaszkow** [comment]
W tym momencie jest używany:
- Primary: biały #FFFFFF
- Accent: zielony #008000
- Danger: czerwony: #FF0000
- Hover: ciemnozielony: #023020
- Border: jasnoszary: #D3D3D3

Tekst:
- Czarny: #000000
- Biały: #FFFFFF

Te kolory są podstawowe bardzo wyraziste, jakbyś chciał coś zmienić to dawaj znać.

**Comment by mateuszstaszkow** [comment]
Do potwierdzenia i można zamknąć
