### ISSUE TITLE
Projekt logo

### ISSUE THREAD

**Issue by mateuszstaszkow** [mateuszstaszkow/ganc_glodowo#5]
Coś w stylu jak tutaj:

![image](https://github.com/user-attachments/assets/a082baa1-418b-4c11-8387-1f4d96cd3e15)

**Comment by mateuszstaszkow** [comment]
Czy chcemy robić jakieś specjalne logo, czy zostawiamy to co jest?

![glodowo-logo](https://github.com/user-attachments/assets/d1ad79e3-5b5b-4fd8-8f0e-4372630546f3)

**Comment by qbuch** [comment]
Logo idealne, ja bym zostawił takie

**Comment by mateuszstaszkow** [comment]
Ok, to zamykam
