### ISSUE TITLE
Dokumenty do załączenia na stronie

### ISSUE THREAD

**Issue by mateuszstaszkow** [mateuszstaszkow/ganc_glodowo#8]
- [x] Zapewnienie dostawy energii elektrycznej i projekt sieci wraz z przyłączami
- [x] Zapewnienia dostaw wody
- [ ] Zgoda na budowę pomostu?
- [ ] Zaświadczenie o przeznaczeniu działek pod tereny zabudowy mieszkaniowej
- [ ] Podstanowienie w sprawie dokonania podziału nieruchomości
- [ ] Projekt podziału działek
- [ ] Miejscowy plan zagospodarowania
- [ ] Komunikacja miejska Rozkład jazdy linii
- [ ] Projekt zjazdu
- [x] Inne?

**Comment by qbuch** [comment]
[decyzja_warunki_zabudowy_280_2.pdf](https://github.com/user-attachments/files/17678079/decyzja_warunki_zabudowy_280_2.pdf)
[energa_zapewnienie_dostaw_280_2.pdf](https://github.com/user-attachments/files/17678081/energa_zapewnienie_dostaw_280_2.pdf)
[warunki_przylaczenia_280_2.pdf](https://github.com/user-attachments/files/17678084/warunki_przylaczenia_280_2.pdf)
Usunąłbym wszystkie punkty poza: zapewnienie dostaw wody,zapewnienie dostaw energii elektrycznej, oraz inne - dodałem plik z warunkami zabudowy które dostaliśmy.

**Comment by mateuszstaszkow** [comment]
W zasadzie w tym momencie to duplikat https://github.com/mateuszstaszkow/ganc_glodowo/issues/19#issuecomment-2464680049, zamykam
